/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.9.0 on Sat May 28 22:30:22 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_final_erpc_service_h_)
#define _final_erpc_service_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief Final_ERPC identifiers */
enum _Final_ERPC_ids
{
    kFinal_ERPC_service_id = 1,
    kFinal_ERPC_Get_data_from_mbed_id = 1,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name Final_ERPC
//@{
float Get_data_from_mbed(uint8_t data);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _final_erpc_service_h_
