# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Sat May 28 22:31:13 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for Final_ERPC
class Final_ERPCClient(interface.IFinal_ERPC):
    def __init__(self, manager):
        super(Final_ERPCClient, self).__init__()
        self._clientManager = manager

    def Get_data_from_mbed(self, data):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GET_DATA_FROM_MBED_ID,
                sequence=request.sequence))
        if data is None:
            raise ValueError("data is None")
        codec.write_uint8(data)

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_float()
        return _result



