# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Sat May 28 22:31:13 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for Final_ERPC
class IFinal_ERPC(object):
    SERVICE_ID = 1
    GET_DATA_FROM_MBED_ID = 1

    def Get_data_from_mbed(self, data):
        raise NotImplementedError()


