# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Sat May 28 22:31:13 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for Final_ERPC
class Final_ERPCService(erpc.server.Service):
    def __init__(self, handler):
        super(Final_ERPCService, self).__init__(interface.IFinal_ERPC.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IFinal_ERPC.GET_DATA_FROM_MBED_ID: self._handle_Get_data_from_mbed,
            }

    def _handle_Get_data_from_mbed(self, sequence, codec):
        # Read incoming parameters.
        data = codec.read_uint8()

        # Invoke user implementation of remote function.
        _result = self._handler.Get_data_from_mbed(data)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IFinal_ERPC.SERVICE_ID,
            request=interface.IFinal_ERPC.GET_DATA_FROM_MBED_ID,
            sequence=sequence))
        codec.write_float(_result)


